### ISSUE TITLE
Error : Error: Class 'XoopsModules\Oledrion\Utility' not found

### ISSUE THREAD

**Issue by scuphy** [XoopsModules25x/oledrion#15]
in 2.35 RC1 
When I uplaod oledrion-master and go to Admin -> System Module -> Modules
show
A problem has occurred on our server!

Error : Error: Class 'XoopsModules\Oledrion\Utility' not found

xoops version v2.5.10
php 5.6 cannot work and try 7.2 the same.
this xoops use cpanel Softaculous install

I try 2.35 Beta 3 can works

**Comment by mambax7** [comment]
You need to rename the folder: 
oledrion-master
to 
oledrion
and try again. 

Github adds the "-master" to indicate the branch.
