### ISSUE TITLE
Top products Error

### ISSUE THREAD

**Issue by Heyula** [XoopsModules25x/oledrion#18]
Error:
Error : Error: Call to a member function getAllCategories() on null

**Debug Mode:**

Error: Error: Call to a member function getAllCategories() on null in file /modules/oledrion/blocks/oledrion_top.php line 66

oledrion/blocks/oledrion_top.php 

` $tblCategories         = $categoryHandler->getAllCategories(new Oledrion\Parameters());`

**Comment by mambax7** [comment]
Should be fixed here:
https://github.com/mambax7/oledrion/commit/b5fe805ad30517a9cec528b3887617c899109076

Thanks for testing and reporting!
