### ISSUE TITLE
Fixed Paypal and many other issues - please merge

### ISSUE THREAD

**Issue by rossbcan** [XoopsModules25x/oledrion#7]
Hi;

Tarball of updates here: https://www.rossco.org/Files/oledrion-2.3.4_BR.tar.gz

Most notable is that Paypal is now tested working (sandbox, my store not yet ready for live), so may actually get some interest / users / testers. And, thanks Mamba for me not being alone on this. It was you who convinced me there may be some hope for Oledrion.

It is my hope that these changes be reviewed and merged into a 2.34 update (for Xoops 2,8) and 2.35. And, that more developers take an interest.
 
Changelog:
Tested with Xoops 2.5.7.1 (2.5.8 required)
Updated Paypal Gateway:
- use current protocols HTTP/1.1, ssl, port 443
- send verification emails after payment cleared (previously before)
- offload payment processing (after paypal confirm) to separate thread to decouple paypal transaction time from total transaction time (due to site load)
- include transaction ID in verification emails
- changed logname to gateway_log.php
- fully tested using sandbox
Do not send validation emails prior to payment verification. May want to re-visit and make config option for scenario's where payment is in escrow until shipped or received.
Changed oledrion_thankyou.tpl and oledrion_cancelpurchase.tpl to links to point to main site URL (whatever is configured as home module, as opposed to OLEDRION_URL) 
Added per-product checkout state override flags (skip_packing, skip_location, skip_delivery) to skip corresponding checkout states to allow a mix of products, some of which may not require these checkout states.
NOTE: have implemented,  but not yet tested creation of above flags @module install, used phpmydamin: tinyint(1), not NULL, default:0.  
Assume that "skip delivery" for all products in cart implies user information fields: first_name, phone_numbers and address are optional, else mandatory at checkout. Collect minimum info for privacy reasons. 
Changed email log path from XOOPS_UPLOAD_PATH to OLEDRION_UPLOAD_PATH
In user invoice (receipt, viewable on site), changed URL of product to be product_url3 (URL  3)from DB (referenced from /modules/, no leading slash), if exists, else original link of form: "$sitename/modules/oledrion/product-id..." (which does not exist unless product description  page created, needs to be created per product). Have not yet tested side-effects, altered basic function "getLink". Implemented since my products are described in publisher articles.
Various bugs fixed. fgrep "B.R." in module dir or diff -rq this_module_dir release_module_dir to see changed files 
TODO / Suggestions:
- Add admin hints when required config such as Packing, location, Delivery are missing which is confusing to users (no way to select, empty radio buttons)
- SMS order notification incomplete. Currently sent before payment verification. Completely rework to add transaction ID (from gateway / paypal) and send after payment verification
- Cannot select more than one gateway (#1). See "TODO" in gateway.php.
- Bug(s) No images can be loaded, all configuration pages. Xoops version?
- fix bug with selecting Picture for payment (admin). May be the wrong place to select picture, since it is used to represent gateway and should be a gateway property (ie; paypal image).
- change templates (checkout) for "Select delivery method form" and "Select payment method form" so that radio button fields are one line each.
- Add stub update DB (at payment verification) function which calls script sh/php for update other DB (such as licensing, access privileges). Consider making gateway or payment config property. 
- Fix receipt email templates such that header and columns line up. Perhaps pretty html option?
- Document this module (not me)

Not the end...
Bill

**Comment by rossbcan** [comment]
Testing update: chasing a paypal bug (paypal/gateway.php)

"if (is_object($commande)) {" : occasionally returns false for valid orders causing transaction not completed from oledrion perspective, completed from Paypal perspective. So, customer believes paid, shop does not.

Have tried (assumed problem is database update timing) a sleep(1) while loop to retry "$commande = $this->handlers->h_oledrion_commands->get($ref);". Same behavior. The transaction ($ref) is valid in DB.

May need some help with this one.

Bill

**Comment by mambax7** [comment]
I've merged your changes to:
https://github.com/XoopsModules25x/oledrion/releases/tag/2.34_Beta-6

Now I'm merging the changes to my branch:
https://github.com/mambax7/oledrion/

Once I'm done, I'll try to look into your issue. Are you testing it in a sandbox, or are these real transactions?

**Comment by rossbcan** [comment]
sandbox. Is there a changelog, or, did U accept all changes? I will continue working the above issue also.

Note that failed (as above) transactions leave evidence files (unsent conf emails) in uploads/oledrion/$order_num_conf_email.parms

**Comment by mambax7** [comment]
Right now I accepted all the changes, for the time being.

**Comment by mambax7** [comment]
You can download this version and test it.  This is the preferred version to test, because that's the one we'll be going forward with. Please check if your changes are properly included:
https://github.com/mambax7/oledrion/releases/tag/2.35_Alpha-1b

**Comment by rossbcan** [comment]
Currently inspecting diffs: my version, your Alpha-1b. Will advise.

Doubt is worth testing Alpha-1b on Xoops-2.5.7.1 Please advise if otherwise. Will test 2.34_Beta-6

**Comment by mambax7** [comment]
The best way for you would be to update to XOOPS 2.5.9 and test the 2.3.5 Alpha 1b there. 
Or set up a test site with XOOPS 2.5.9 and test it there. 
I would not invest more time into 2.34_Beta-6 and Xoops-2.5.7.1.

**Comment by rossbcan** [comment]
Yeah; gonna have to bite the bullet (soon) and upgrade Xoops (this means: new sme-server (php, ptyhon versions), porting a lot of custom stuff, modules, filters to auto create TOC's for publisher articles, Popup definitions...). Cannot happen within next month, personal life demands (wife, vacation, family) will make me unavailable Jun 16 to 26.

Before then: intend to inspect / verify my changes by you, implement stub DB update and fix Paypal bug.

Re the DB update function. Will require it be a php file, used thusly:
                                            if (file_exists(OLEDRION_DB_UPDATE_SCRIPT)) {
                                                  include OLEDRION_DB_UPDATE_SCRIPT;
                                                  // updateDB($product_id, $user_id, $transaction_id);
                                                  $log .= updateDB($ref, $_POST['receiver_email'], $_POST['txn_id']);
                                            }
where OLEDRION_DB_UPDATE_SCRIPT is manually set in config.php
    // B.R. New: Absolute path and filename of optional database update script
    // Must be located outside DOCUMENT_ROOT and change permissions to 'rwxr-x--x'
    define('OLEDRION_DB_UPDATE_SCRIPT', '/absolute path/update_licenseDB.php');

Any script security concerns / suggestions regarding this approach?

..B

**Comment by rossbcan** [comment]
You moved / renamed some files, found all my changes in these, good (Alpha-1b) unless comment:
admin/actions/products.php
admin/actions/vat.php
class/CommandsHandler.php
class/Gateways/Paypal/Paypal.php
class/Gateways.php
class/Products.php
class/Reductions.php - redundant "GetDatabaseConnection", lines 441, 454)
class/Utility.php
language/english/mail_template/command_client.tpl - update Persian, or add to TODO list
language/english/mail_template/command_shop.tpl - update Persian, or add to TODO list
sql/mysql.sql
templates/oledrion_cancelpurchase.tpl - suggestion: nuke "oledrion_", all filenames in templates
templates/oledrion_thankyou.tpl
checkout.php
config.php
In general: much cleaner Xoops 2.5.9, with PHP 7
FYI: I recommend Beyond compare from Scooter Software (https://www.scootersoftware.com/) for reconciling distribution version tasks.

**Comment by rossbcan** [comment]
Update: http://www.rossco.org/Files/oledrion-2.3.4_BR-1.tar.gz

changed: paypal/gateway.php
1 - still having intermittent "not object" failures discussed above, which previously resulted in lost transactions. Now, return error to Paypal so Paypal retries.

2 - added support for (non-xoops) DB update script to update licensing and access DB's.

Bill

**Comment by mambax7** [comment]
Unfortunately, this not going to work :( 
It took me several hours to update the current versions (2.34 and 2.35) with your code, assuming that you'll take at least the updated version 2.34 (but I was hoping for the 2.35)  and add any future changes to that, so at least my extra hours were not for nothing.
Your current version that you just submitted, is still the old version, i.e. I would have to start from zero and do it again, but unfortunately, I don't have the time :( 

So the best way would be for you to fork on GitHub the version 2.35 from https://github.com/mambax7/oledrion and and use your local Git to add your changes and then submit "Pull Proposal" 
This is very easy, and I'll be glad to help/coach you step by step, so you can start using GitHub, as it is much more productive for both of us. 
Are you using Windows or Linux for your development?

**Comment by mambax7** [comment]
I've added your Paypal changes to 2.35 on https://github.com/mambax7/oledrion
the exact link is: https://github.com/mambax7/oledrion/commit/b239ebba892229e30811967c4d39a287f852383c

**Comment by mambax7** [comment]
FYI: The function "updateDB" was not found.

**Comment by rossbcan** [comment]
Hi Mamba;
Thanks;

Write an example stub php file to include with it that accepts parameters shown (gateway.php) and returns a result string. As a DB update function, it will contain sensitive credentials. I have tested the API and, transactions update my DB and, results string in gateway logfile. Also, function not called if file not exist.

Be aware it will be at least a month before I can test 2.35. Will inspect 2.35 gateway.php and advise.

...B

**Comment by rossbcan** [comment]
Hi Mamba;

Gateways\Paypal\Paypal.php feedback:
1 - Inconsistent usage of $_POST versus \Xmf\Request::
2 - Inconsistent usage of "= array();" versus "= [];" (your other ports use the latter)
3 - Using R.B start / end instead of B.R. I placed these comments for you, can delete.
4 - Remaining commented portions of previous version confusing and of no use. Delete lines: 347-352, 392-396, 399-404, 412

I took the liberty of fixing issues 3, 4. You can just replace the file and use your own discretion for issues 1, 2: http://www.rossco.org/Files/Paypal.php.txt

Also, I placed my DB update script (minus sensitive info) online. You can use this as an example template, or modify: http://www.rossco.org/Files/updateDB.php.txt

Regards;
Bill
